### ISSUE TITLE
Error with upload

### ISSUE THREAD

**Issue by Jhonatan-Souza** [habom2310/Heart-rate-measurement-using-camera#14]
I try to run and open and upload a video, this error happens. 

Heart-rate-measurement-using-camera-master/GUI.py", line 210, in openFileDialog
    self.statusBar.showMessage("File name: " + self.dirname,5000)
TypeError: can only concatenate str (not "tuple") to str

**Comment by Raevel** [comment]
Did you find a solution? i'm trying to input a video sample but the software crashes everytime. Should i use a specific format or resolution?

**Comment by habom2310** [comment]
I've just had a quick look and found that it was an error related to the difference between pyqt versions. I've just updated the code. You can pull and try again.

**Comment by Raevel** [comment]
Pulled and tried again, same PyQt version but still not working. Still crashes everytime i click on Start to upload a video. 

C:\Users\Francesco\anaconda3\envs\env_dlib\python.exe C:/Users/Francesco/Desktop/Webcam/GUI.py
Input: webcam
Input: video
Start video

Process finished with exit code -1073740791 (0xC0000409)

**Comment by arashtavakoli** [comment]
Same issue

**Comment by Peipeilvcm** [comment]
you can print(self.dirname), and you will find that self.dirname is a tuple.

self.dirname[0] works well

**Comment by arashtavakoli** [comment]
It's the GUI, are you referring to change the underlying python code?

**Comment by arashtavakoli** [comment]
yeah it works, for whoever wants to know, go under video.py and add [0] to this line:
self.cap = cv2.VideoCapture(self.dirname[0])
